#include<stdio.h>
int main()
{
    int a=60,b=70,c=80,d=40,e=50;
    if(a>b)
    {
        if(a>c)
        {
            if(a>d)
            {
                if(a>e)
                {
                    printf("A");
                }
                else
                {
                    printf("E");
                }
            }
            else
            {
                if(d>e)
                {
                    printf("D");
                }
                else
                {
                    printf("E");
                }
            }
        }
        else
        {
            if(c>d)
            {
                if(c>e)
                {
                    printf("C");
                }
                else
                {
                    printf("E");
                }
            }
            else
            {
                if(d>e)
                {
                    printf("D");
                }
                else
                {
                    printf("E");
                }
           } 
        }

    }
    else
    {
        if(b>c)
        {
            if(b>d)
            {
                if(b>e)
                {
                    printf("B");
                }
                else
                {
                    printf("E");
                }
            }
            else
            {
                if(d>e)
                {
                    printf("D");
                }
                else
                {
                    printf("E");
                }
            }
        }
        else
        {
            if(c>d)
            {
                if(c>e)
                {
                    printf("C");
                }
                else
                {
                    printf("E");
                }
            }
            else
            {
                if(d>e)
                {
                    printf("D");
                }
                else
                {
                    printf("E");
                }
            }
        }
    }
}