#include<stdio.h>
int main()
{
    int a=10,b=9,c=3,d=4,e=1;
    if(a<b)
    {
        if(a<c)
        {
            if(a<d)
            {
                if(a<e)
                {
                    printf("A");
                }
                else
                {
                    printf("E");
                }
            }
            else
            {
                if(d<e)
                {
                    printf("D");
                }
                else
                {
                    printf("E");
                }
            }
        }
        else
        {
            if(c<d)
            {
                if(c<e)
                {
                    printf("C");
                }
                else
                {
                    printf("E");
                }
            }
            else
            {
                if(d<e)
                {
                    printf("D");
                }
                else
                {
                    printf("E");
                }
            }
        }
    }
    else
    {
        if(b<c)
        {
            if(b<d)
            {
                if(b<e)
                {
                    printf("B");
                }
                else
                {
                    printf("E");
                }
            }
            else
            {
                if(d<e)
                {
                    printf("D");
                }
                else
                {
                    printf("E");
                }
            }
        }
        else
        {
            if(c<d)
            {
                if(c<e)
                {
                    printf("C");
                }
                else
                {
                    printf("E");
                }
           }
           else
           {
             if(d<e)
            { 
                printf("D");
            }
            else
            {
                printf("E");
            }
           }  
        }
    }
}